# Site settings
title:              site title
description:        "site description"
logo:
baseurl:            "" # the subpath of your site, e.g. /blog/
url:                "http://localhost:4000" # the base hostname & protocol for your site
search:             true
share:              true
readtime:           true
wpm:                200 # Specify the average Words per minute. If not defined, 180 will be used
default_bg:         me.jpg
exclude:			["node_modules", "gulpfile.js", "package.json"]

# Build settings
highlighter:        pygments
markdown:           rdiscount

# Owner/author information
owner:
name:
avatar:
email:

# Social networking links used in footer. Update and remove as you like.
# For Google Authorship https://plus.google.com/authorship
facebook:
twitter:
github:
google_plus:
linkedin:
instagram:

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-00000000-1
google_verify:
bing_verify:


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Edmonton
future:             true
paginate:           6
paginate_path:      "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:          /:categories/:title